### ISSUE TITLE
Protocol tests

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#100]
A set of tests which don't use the Mewbase client but send and receive frames directly to a Mewbase server and assert the correct things are returned, e.g. responses and acks.

**Comment by NigeWarren** [comment]
Some of this could be 'proved' by implementing another client with reference to the protocol.md rather than the Java code. For example a JavaScript, Elixir, Go or other Client, that was implemented independently of the Java codebase.

**Comment by NigeWarren** [comment]
Protocol has become the wire protocol of the underlying Event system (default Nats Streaming)

This brings with it clients for the above lanagauges ( and others ) https://nats.io/download/
