### ISSUE TITLE
Binder tests fail on windows 10

### ISSUE THREAD

**Issue by ricardoffmartins** [Tesco/mewbase#127]
Software IntelliJ 2017 Community Edition
JDK 1.8

When we run the Binder tests, most of them fail because of an NullPointerException on this line of code:
Binder binder1 = store.open(BINDER_NAME).get();

This line is common on the following tests:
testFindNoEntry()
testOpenBinders()
testSimplePutGet()
testBinderIsPersistent()
testDelete()
testGetIds()
testPutGetDifferentBinders()

However this does not occur on Macs and Linux. 

The stacktrace for the testPutGetDifferentBinders test: 

testPutGetDifferentBinders(io.mewbase.binder.BindersTest)  Time elapsed: 0.029 sec  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.mewbase.binder.BindersTest.testPutGetDifferentBinders(BindersTest.java:159)
Caused by: java.lang.NullPointerException: null
	at io.mewbase.binders.impl.lmdb.LmdbBinder.<init>(LmdbBinder.java:56)
	at io.mewbase.binders.impl.lmdb.LmdbBinderStore.lambda$null$2(LmdbBinderStore.java:89)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.mewbase.binders.impl.lmdb.LmdbBinderStore.lambda$open$3(LmdbBinderStore.java:89)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by NigeWarren** [comment]
Thanks Ricardo -  Ill have find a windows machine to test - any more info or debugging like the version bumber of windows 10 would be helpful

**Comment by ricardoffmartins** [comment]
Sorry, tottaly forgot about the version. 

Windows Edition: Windows 10 Pro
Version: 1703
SO compilation: 15063.608

**Comment by ricardoffmartins** [comment]
The bug related with this problem is solved when we reduce the size of _DEFAULT_MAX_BINDER_SIZE_ in MewbaseOptions.java. The value is set to allow a max size of 1 terabyte (1024L * 1024L * 1024L * 1024L), but if we reduce the size to 1 Gigabyte (1024L * 1024L * 1024L) the bug no longer occurs.

**Comment by NigeWarren** [comment]
Very interesting @ricardoffmartins - looks like it relates to some constraint set by the filesystem in Windows - we can either find the default value for Windows and set it to that or you could binary chop to the max value relatively quickly.

**Comment by ricardoffmartins** [comment]
I searched for some default value for the max db size for windows and i didnt really found anything but i tried a binary chop to find some limit value and my conclusion is that it depends on the computer storage. 
The default value was set to 1 Terabyte, and my computer has a disk of 930GB. when i try to run the tests, these fail because my computer can not store these amounts. However when i change the value to 1GB, it works until the disk is full. After running the tests two or three times my Temp folder gets full, something like 880GB ocupied, and if we run the tests again, these fail again. 
My process to detect this was to clean the Temp folder by going to Settings, System, Storage, selecting the Disk of interest and cleaning the Temp folders. Then we can run the tests several times. After some time, these tests will start to fail, and if we check the Temp folder we see that it is full.

**Comment by NigeWarren** [comment]
Thanks @ricardoffmartins - is the size of the files that get created the size of DEFAULT_MAX_BINDER_SIZE ? Sounds a little inconsistent to me.

In the tests you could delete the contents of the folder that is created from that test, for example.
If you look in MewbaseTestBase in tests you will set the setup code for the temp directory.

If you check the contributor guide (CLA) in the project and PR a fix I'd be very happy to merge your fix to master when complete.

**Comment by ricardoffmartins** [comment]
Hello @NigeWarren 
The folder the were created during tests had two files inside, a data.mdb and a Lock.mdb. The data.mdb always have the size of DEFAULT_MAX_BINDER_SIZE. In my case 1 GB. I found some inconsistencies in the tests, like some tests call the store.close() to close connections, others did not. But this wasn't the main problem. One major cause for not being able to delete the folders were two line of code in LmdbBinderStore in the close() method, line 130 and 132:

130: Set<CompletableFuture<Void>> all = binders().map(binder -> ((LmdbBinder)binder).close()).collect(Collectors.toSet());

132: CompletableFuture.allOf(all.toArray(new CompletableFuture[all.size()])).get();

The second line of code was blocking the test and the program never called the several close() methods in the 'finally' scope. 

Changing these two lines to:
Stream<CompletableFuture<Void>> all = binders().map(binder -> ((LmdbBinder)binder).close());

Seems to solve the blocking problem. 
After adding the Store.close() to the remaining tests, all tests in BinderTests delete the created folders.
But several tests in Mewbase didn't delete the created folders. Some errors occur due to the start() method in ServerImpl. 

line 71:   Runtime.getRuntime().addShutdownHook(new Thread(this::stop))

This error occur when the @After method of the test class was called, calling server.stop(), and then the program executed this Thread created in the start() method, making the program to crash. I commented this line and it looks ok, but i don't really understand the implications of commenting this line. So i don't know if this is the correct thing to do. 

So, initially almost any test deleted the created folders. At this moment only a few folders aren't yet being deleted. On Monday I intend to test these changes on a Mac. And to check if i see any of these behaviours on a Mac.

**Comment by NigeWarren** [comment]
Thanks Ricardo - It would be preferable that the resources get close wether or not the library user calls close in the test. This would guard someone writing a client that doesnt call close but still quits the program.

Also the tests really should run independently of the server code. I.e. all the tests should run as MewbaseTestBase(s) not ServerTestBase(s) HTH

**Comment by ricardoffmartins** [comment]
Hi @NigeWarren . I haven't test my changes on a Mac yet but your answer left me with some doubts. When you say that tests should run as MewbaseTestBase and not ServerTestBase, you mean the LMDBBinderTests, or all tests? Because some tests need the server code.

**Comment by NigeWarren** [comment]
Hi @ricardoffmartins - In this case I was referring to the BinderTests but I understand that some other tests still use the ServerTestBase. Of course the Server Tests should only be dependent on the ServerTestBase. I see the problem though. 
If we make the MewbaseTestBase be responsible for managing the Binder Storage in the tests then that should cover the other cases, unless Im misled in some way ?

**Comment by ricardoffmartins** [comment]
Hello @NigeWarren, I have tested my changes in Macs and right now Mewbase is working in Windows and deleting all Temporary Folders created. Im preparing a PR and i would like to know how does the contributor guide (CLA) work, do i have to print it, sign it and put it inside the project, replacing the CLA.txt that already exists? Or do i sent it separately?
