### ISSUE TITLE
Event selectors for subscriptions

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#13]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 10:48 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/13_

---

It should be possible to choose the specific type of events accepted by a subscription. We should allow matching based on:
- exact event type match
- event type max using regex
- match on structure of event using a BSON matcher object (like in queries). This can provide same matching semantics as when querying docs.

**Comment by NigeWarren** [comment]
For both Queries and Event Streams we have implemented 'Named' filters in the Server and access to the Filter via the name in the API - removing he need for BSON matching objects in the API.
Closing under #119 and #121
