### ISSUE TITLE
Async Java for EventSink

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#17]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 10:53 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/17_

---

Create a wrapper around the Java client that provides a blocking API - for those users that prefer a blocking API.

**Comment by NigeWarren** [comment]
Flipped this one round 
EventSink currently has Sync support but no Async Support so complete the pictures as per this feature request we need to implement Async Support for EvetnSink.

**Comment by NigeWarren** [comment]
Completed by #134
