### ISSUE TITLE
SQL injection in Postgres Binder

### ISSUE THREAD

**Issue by mcarolan** [Tesco/mewbase#170]
SQL injection is currently possible in a couple of places in `PostgresBinder`

An example being:
https://github.com/Tesco/mewbase/blob/master/mewbase-core/src/main/java/io/mewbase/binders/impl/postgres/PostgresBinder.java#L63

It's easy to rectify using a `PreparedStatement` when the value is to be injected at condition position (e.g. `WHERE key = '"+id+"';`).

However in other cases values are injected at table name position (e.g. `INSERT INTO "+name+" VALUES`) as there is a table per binder. This is more problematic as JDBC drivers do not allow parameterisation in this position.

A couple of potential solutions could be:

1. Restrict binder names to be, e.g., alphanumeric and continue in current manner
2. Use a single table (indexed on binder name), shared between all binders

Would be interested to hear thoughts and other solutions, and happy to work on a PR to solve this issue

**Comment by kings13y** [comment]
Fixed. Closing.
