### ISSUE TITLE
Client caching of queries

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#19]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 10:55 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/19_

---

We should allow some query results to be cached in the client so subsequent requests don't always have to go to the server.

**Comment by NigeWarren** [comment]
Would query caching be dependent on being updated if a change was made to a document ?
If we did #20  then I guess this becomes possible/simple to implement because we can replace outdated docs in the cache when notified of the change
