### ISSUE TITLE
Live query results on client

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#20]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 10:57 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/20_

---

We should consider allowing the client to return "live" query results. These are results from views which automatically update as the views change on the server.
This can be implemented by sending a stream of update events from server to client as the view changes.

**Comment by NigeWarren** [comment]
Yes please - the ability to "subscribe" in some way to a document and listen for updates on a stream 

If the result of the Projection changes the state of the doc then the document is sent to the clients stream. 

Maybe also the ability to register interest if certain 'fields' of the doc changes.

For certain patterns documents from one server become the events to another and then we are most of the way to a 'data telescope'  or 'data trellis' 

https://cacm.acm.org/magazines/2001/11/7215-a-computational-model-of-everything/abstract
e.g.
https://uthealth.influuent.utsystem.edu/en/publications/a-parallel-software-architecture-for-building-intelligent-medical

**Comment by NigeWarren** [comment]
Closed in the light of #130
