### ISSUE TITLE
Lazy BSON parser

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#30]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:08 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/30_

---

We should implement a lazy BSON parser.

When taking events from a client, persisting to event log and distributing to subscribers, there's no need to decode the entire BSON object - just the first few fields are needed to do this - the rest can be kept as a buffer.

Right now we are decoding/encoding the entire object which is inefficient.

We should create a lazy bson parser which decodes fields from a buffer only when needed.

**Comment by NigeWarren** [comment]
Also relates to Bson path - These are solved by the generalised case of Streaming Parsers which is being developed in the Boson library hence suggest we use that when it becomes stable.

Deprecating BsonPath since 0.2.1.
