### ISSUE TITLE
Pluggable authentication\authorisation

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#31]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:09 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/31_

---

We should provide interface hooks so auth can be plugged into the server.

**Comment by nmarquesantos** [comment]
taking a look, already had a chat on irc

**Comment by purplefox** [comment]
hi @nmarquesantos just wondering how the authorisation was going :)

**Comment by nmarquesantos** [comment]
hi @purplefox i've been trying to notify you via IRC but it seems I'm never able to catch you there hehe

I've been very busy and not a lot of free time to spend on mewbase.

I'm hoping to get the solution on first week of Jan is that's ok. (had to travel without laptop)
