### ISSUE TITLE
Implement TLS for connections

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#35]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:12 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/35_

---

With server and client certificates

**Comment by nmarquesantos** [comment]
I'll have a look at this as per http://vertx.io/docs/vertx-core/java/#ssl

I'll give it a go with openSSL and pem files

**Comment by purplefox** [comment]
If you need any help just ping me. irc would be best
