### ISSUE TITLE
Performance test suite

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#36]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:20 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/36_

---

Create a performance test suite that can be run both locally and on AWS.

**Comment by NigeWarren** [comment]
We have just set up a performance test suite (single perf test) in the mewbase-perf project mostly for the purposes of making sure that extensions to the functionality don't adversely effect the performance of the system. This certainly works locally and may well work on AWS however I take this imply somthing more along the lines of a local/remote test with an automated testing framework (gatling, cucumber, postman, ???)

**Comment by NigeWarren** [comment]
Answered with https://github.com/Tesco/mewbase-perf
