### ISSUE TITLE
Metrics gathering

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#38]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:21 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/38_

---

Enable several points in the server to emit metrics events - these can be stored in streams and then we can maintain views of them in documents just like any other views

**Comment by NigeWarren** [comment]
Should look at using Spring Boot 2 - Micrometer Library to patch into the

**Comment by NigeWarren** [comment]
Given that we are going to implement another REST api in Spring Boot - then it would make sense to use the instrumentation from this library to avoid what is mpostly a lightweight system becoming depenedent on the "world" of Maven.

**Comment by NigeWarren** [comment]
Doing this on the 'instrument' branch - using 'shims' to patch the main abstractions with counters that can be later used to do quotas #12 and stats #26

**Comment by NigeWarren** [comment]
Using Micrometer Library which will allow access via a local data collector to all the instrumentation ready for stats in systems docs #26

**Comment by NigeWarren** [comment]
Closed with merged #184
