### ISSUE TITLE
High availability support

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#40]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:23 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/40_

---

We should provide an interface which allows partition leaders in a cluster to be selected.

We should provide an initial implementation that uses Zookeeper

**Comment by NigeWarren** [comment]
Since making Mewbase into a Library over Event and Document stores. We move HA to the underlying Storage implementations. e.g. 

The Nats implementation of EventSource has HA mode with leader election.
