### ISSUE TITLE
Server replication

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#41]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:28 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/41_

---

Implement server replication where some servers can be leaders, and others followers. The followers replicate logs on the server.

We should allow all document and event logs to be replicated.

Replication can be implemented by the follower subscribing to events on the leader and then updating their own logs locally.

When the changes have been written to the logs an ack should be sent back to the leader. This should all be pipelined and async so we don't have RTT latency for every operation.

It should be configurable to send ack back to leader when either:
1. entry has actually been persisted to disk
2. entry has been accepted on replica and will be persisted to disk asynchronously
3. will provide better durability guarantees (no loss if the entire data centre goes down)
4. will provide better performance.

**Comment by NigeWarren** [comment]
Now that mewbase is a library this has gone beyond scope and has moved to the underlying Event store.
