### ISSUE TITLE
Server sharding/partitioning

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#42]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:31 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/42_

---

It should be possible to partition streams across multiple physical servers.

This is important for horizontal scalability in the case where a stream expects a lot of events - too many to be supported by a single log.

In this case, the client can select an actual server to emit an event to based on consistent hashing of some value. It should be possible to specify which field(s) in an event to use in the hashing.

E.g. you might want to hash on customerID in a place order event.

**Comment by NigeWarren** [comment]
Sharding and partitioning are now handled by the underlying implementation of the Event Stream and the Binder Store
