### ISSUE TITLE
Subscription groups

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#43]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:34 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/43_

---

It should be possible to specify a subscription group when creating a subscription.

The server will then guarantee that only one subscription with the same value of the group will receive a particular event when streaming.

If there is more than one subscription with the same group value one can be chosen in a round robin way when distributing.

This can be used to implement exclusive consumers or balancing load across consumers.

See https://activemq.apache.org/artemis/docs/1.0.0/message-grouping.html

**Comment by NigeWarren** [comment]
Subscription Groups now handled by Nats or underlying Event Source and Sink
