### ISSUE TITLE
Durable subscriptions

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#44]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 11:37 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/44_

---

It should be possible for subscriptions to be durable.

That is, a client can resume subscribing from the last message acked in a subscription, even after a restart of the server or client.

This can be implemented by the server persisting last acked id on the server side in a system document.

In the case of reconnection after a failure some messages may be redelivered but no messages will be lost.

Mewbase provides "at least once" delivery semantics.

**Comment by ssouris** [comment]
Hi (we started talking on the google group about this issue).

I  have some questions. 
Where will `last message acked` be persisted? Temporary document database that is talked about in other issue(s)?
Will there be retries on re-subscription?

**Comment by purplefox** [comment]
Hi Souris,

Yes I think we should store the last acked id in a document (one document per subscription) in a binder in the docmanager.

I imagine the document will contain the following information:

{
clientID: "abc12345" <- primary key
lastAckedSequence: 123
}

Right now the docmanager is in memory only, so it won't actually work between restarts, but the code can still be written and tested with just resubscribes instead of restarts.

On resubscription, the client provides the client id - the document is then looked up from the docmanager and the lastAckedSequence is retrieved, the subscription is then restarted from that point.

**Comment by purplefox** [comment]
Hi @ssouris just wondering how you're doing on this. If you need any help just ask :)

**Comment by ssouris** [comment]
Hi Tim, sorry for not getting back to you but I am in the middle of a relocation. I hope by the end of this week I will be wired and coding :)

**Comment by purplefox** [comment]
No problem! If you haven't started this yet, can I ask you to choose another task? I kind of need this one to be complete by the end of the week

**Comment by ssouris** [comment]
Ok then, better give this task to someone else, since I don't have much time right now. Thanks

**Comment by purplefox** [comment]
Thanks, I quite understand you're busy. If you ping back when you have a bit more time we can find something else for you to do that's not so much on the critical path :)
