### ISSUE TITLE
Sequential file read/write tests

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#55]
We should do a simple benchmark testing different strategies for reading/writing from sequential files so we can choose the optimal strategy for append only logs.

Strategies should include:
1. RandomAccessFile
2. Memory mapped files
3. java.io bufferedstreams
4. AsynchronouseFileChannel
5. Vert.x asyncfiles
6. Linux async IO via JNI

Test should preallocate a large file then:
1. write several gb
2. read several gb

(The sync tests should also deliver their results to another thread via a queue as that is what we do it in a real server)

We should also test performance with fsync'ing enabled.

We should run the test on AWS and a server configured with RAID array.

**Comment by chirino** [comment]
If you require all logs to be replicate across AZs, then then perhaps the requirement to fsync is moot.  You'll end up with way better disk IO efficiency which is something that you need to consider scaling write heavy use cases.

**Comment by purplefox** [comment]
Yes absolutely, fsync'ing should be optional so we can support the replicated log setup where typically most people don't bother fsyncing.

Although some people will want to be fsync e.g. if they're running on a single server and want to delegate reliability to the storage layer, or perhaps because replication doesn't give them the guarantess they want (what if the AWS storage layer goes down at same time on both replicas?)

**Comment by chirino** [comment]
Well, I think it's accepted that replication can only survive a given number of failures.  I'm sure someone smarter than me can calculate the probability of concurrent failures across 2 AWS AZs.

**Comment by purplefox** [comment]
The thing with replication is the replicas really need to be independent
and often there are hidden dependencies which means both replicas might go
down at the same time, e.g. the whole EBS system goes down at once, or some
other dependency no one has thought of.

Also.. without fsync it might be 30 seconds or more before data makes it to
permanent storage (when the OS decides to flush the buffers), this means
failures don't have to be really concurrent to get data loss, they just
have to occur within a much larger time window, which increases the
probability of data loss.

Granted though, this level of durability is good enough for most people,
but not for everyone, hence I think it needs to be configurable, but
default can be "nosync" (or async sync)
