### ISSUE TITLE
Event log: corruption detection

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#60]
Implement detection of corrupt log records, e.g. by CRC32 checking

**Comment by purplefox** [comment]
A simple way to do this initially would be:

1. on startup if shutdown=false then it means the server did not shutdown correctly.
2. read lastWrittenPos from the info file and zero out all records in the log after that and reset headPos to the end of the record started at lastWrittenPos.

I don't think CRC checks are really necessary (?)

**Comment by MyAtomicMother** [comment]
I agree with the simple check you have proposed.
Trying to wrap my head around the different ways corruption can occur - is there a doc regarding the client server interaction patterns? Like different kinds of read/write patterns possible

**Comment by purplefox** [comment]
I think there are different ways the log can become corrupt:

1. The server is terminated abruptly in mid write resulting in partial writes in the log. E.g. only half of a document is written
2. The HDD/SSD partially fails in some way losing data.
3. User error / malicious editing. User accidentally or deliberately changes the log file in some way

2 - Aiui, the storage device will normally detect bad sectors using its own methods (e.g. CRC) and flag them. Not much for us to do here?

3 - Not much for us to do here - if a user has access to the log directory they can do anything anyway.

1 - This is the main situation we need to deal with (possible solution described above)

**Comment by purplefox** [comment]
Hi @MyAtomicMother just wondering how you're doing with this :)

**Comment by purplefox** [comment]
On second thoughts we should probably allow for CRC checking

**Comment by NigeWarren** [comment]
Status - The branch 'binary-pipeline' contains the code for Checksum headers and Magic number footers making a frame around each event. The checksum obviously relates to the above comments and the magic number 128 bits relates to the case (from above)
-The server is terminated abruptly in mid write resulting in partial writes in the log. E.g. only half of a document is written.
Where the Magic number allows readers of the file to accurately detect the end of one valid record and hence the start of a possibly invalid record.

**Comment by NigeWarren** [comment]
Closing this under #117
