### ISSUE TITLE
In-VM transport

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#8]
<a href="https://github.dev.global.tesco.org/baj0"><img src="https://github.dev.global.tesco.org/avatars/u/2087?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [baj0](https://github.dev.global.tesco.org/baj0)**
_Sunday Oct 02, 2016 at 10:41 GMT_
_Originally opened as https://github.dev.global.tesco.org/baj0/mewbase/issues/8_

---

Create an in-VM transport for clients that are in the same JVM as the server to avoid going over sockets/whatnot.

**Comment by NigeWarren** [comment]
This would  need some tests to ensure that we were "optimising" at the right level. I get the strong suspicion that a better Bson encoder and parser e.g. as per #84  would give us more speed without the need for specialised code.

**Comment by NigeWarren** [comment]
As of 0.2.1 the remote layer has been moved to REST hence this is no longer applicable
