### ISSUE TITLE
Simplify server config

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#81]
Combine FileLogManagerOptions into ServerOptions.

Also there are various hardcoded params scattered throughout the code, we should make those configurable.

**Comment by MyUmmaGumma** [comment]
Combine FileLogManagerOptions into ServerOptions.: https://github.com/Tesco/mewbase/pull/87

Can we move the hardcoded param aggregation to a separate task?

**Comment by purplefox** [comment]
On Mon, Nov 21, 2016 at 11:41 PM, MyUmmaGumma <notifications@github.com>
wrote:

> Combine FileLogManagerOptions into ServerOptions.: #87
> <https://github.com/Tesco/mewbase/pull/87>
>
> Can we move the hardcoded param aggregation to a separate task?
>


That's fine. Feel free to add a new issue

**Comment by MyUmmaGumma** [comment]
Tim, I created a new user and patched the changes in on a new PR. 
https://github.com/Tesco/mewbase/pull/97

Can we close this PR and use that for Issue 81 instead?
