### ISSUE TITLE
Fully implement BsonPath

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#84]

**Comment by purplefox** [comment]
Hi @jcme if you want to chat about this in more depth I'd be happy to do that, I appreciated my description of the task was very vague! ;)

**Comment by jcme** [comment]
Hey @purplefox that probably would be very useful - thanks! I've used our brief mIRC conversation for some rough notes, but a slightly more detailed chat would probably help set me off in the right direction. Any chance you're in Welwyn before Christmas? We could grab a quick coffee

**Comment by purplefox** [comment]
Unfortunately I won't be in the office until the New Year now :(

The original idea behind BsonPath was a bit like JsonPath http://jsonpath.com/ - a way to match/select/update elements in Bson documents.

An example is in our shopping basket example, here we want to increment the quantity of a product in a basket document when an event comes in.

A shopping basket might look like this:

````
{
    "basketID": 1256125
    "products": {
        "product1", 12
        "product435", 1
        "product32", 2
    }
}
````

If we want to increment the quantity of product435 with BsonPath we can just say:

````
BsonPath.add(basket, 2, "products", "product435");
````

Whereas if we had to do that by manipulating the BsonObject directly (or just using a Map) then it would be a lot uglier:

````
BsonObject products = basket.getBsonObject("products");
if (products == null) {
    products = new BsonObject();
    basket.put("products", products");
}
Integer currentQuantity = products.get("product435");
if (currentQuantity == null) {
    currentQuantity = 1;
}
currentQuantity++;
products.put("product435", currentQuantity);

````

(Internally that's more or less what BsonPath does).

So it's all about making it easier for the user to manipulate Bson objects.

Currently the path in BsonPath is represented as a list of vararg parameters, but we can also support representing a path as a string (like JsonPath does).

There's a lot of scope for the kinds of operations we can support here, I think initially it would be good to have:

get
set (already have this)
add (already have this)
remove

just working on a static path

we can also have matching operations, e.g.

```
boolean matches(BsonObject bsonObject, String... somePath)
````

Matches will be useful in implementing queries amongst other things.

Just some ideas.

**Comment by purplefox** [comment]
BTW, if you want something a bit smaller we can find you another task too. Up to you :)
