### ISSUE TITLE
Client version checking on CONNECT

### ISSUE THREAD

**Issue by purplefox** [Tesco/mewbase#89]
Client version should be checked on CONNECT and if not compatible, an error RESPONSE should be sent and the connection closed

**Comment by ssouris** [comment]
Hi Tim,

I would like to get involved in this issue.
How will the server find client compatibility? Will there be a version range that will be compatible with the server?

Thanks

**Comment by purplefox** [comment]
We can do something like we do in Vert.x: The server and client can know the version from a version.txt file built into the jar, which is loaded from the classpath.

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/launcher/commands/VersionCommand.java#L53

For knowing which client versions are compatible we can just have a simple implementation for now,e .g. check client version <= server versioin.
